"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// `npx soloship upgrade`. Shared normalize/detect/emit helpers every gate
// file in this directory requires. See src/committed-gates.ts in the
// Soloship repo for the source of truth and full rationale.

const fs = require("fs");

function readStdin() {
  try {
    return fs.readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function detectHost(data) {
  if (data && typeof data === "object" && data.toolCall && typeof data.toolCall === "object") {
    return "antigravity";
  }
  if (data && typeof data === "object" && typeof data.command === "string" && data.tool_input === undefined) {
    return "cursor";
  }
  return "claude"; // covers Claude Code + Codex CLI (identical contract), and any unrecognized shape
}

function normalize(host, raw) {
  let data = {};
  try {
    data = raw ? JSON.parse(raw) : {};
  } catch {
    data = {};
  }
  if (host === "cursor") {
    return {
      toolInput: {
        command: data.command || "",
        filePath: data.file_path || data.filePath || "",
        content: data.content ?? "",
      },
      cwd: (data.workspace_roots && data.workspace_roots[0]) || data.cwd || process.cwd(),
      sessionId: data.conversation_id || "",
    };
  }
  if (host === "antigravity") {
    const call = data.toolCall || {};
    const args = call.args || {};
    return {
      toolInput: {
        command: args.CommandLine || "",
        filePath: args.TargetFile || args.AbsolutePath || "",
        content: args.CodeContent || args.ReplacementContent || "",
      },
      cwd: data.cwd || process.cwd(),
      sessionId: data.session_id || "",
    };
  }
  // claude / codex
  const ti = data.tool_input || {};
  return {
    toolInput: {
      command: ti.command || "",
      filePath: ti.file_path || "",
      content: ti.content ?? ti.file_text ?? ti.new_string ?? "",
    },
    cwd: data.cwd || process.cwd(),
    sessionId: data.session_id || "",
  };
}

// verdict: {block: boolean, message?: string, warn?: boolean}
// warn (without block) surfaces `message` as a non-blocking systemMessage on
// hosts that support it (Claude, Codex); Cursor and Antigravity have no
// non-blocking-message channel in their current hook contracts, so warn is a
// silent no-op there rather than a fabricated block.
function emit(host, verdict) {
  const block = !!(verdict && verdict.block);
  const warn = !!(verdict && verdict.warn);
  const message = (verdict && verdict.message) || "";
  if (host === "cursor") {
    process.stdout.write(
      JSON.stringify(
        block
          ? { permission: "deny", user_message: message, agent_message: message }
          : { permission: "allow" }
      )
    );
    process.exit(0);
  }
  if (host === "antigravity") {
    process.stdout.write(
      JSON.stringify(block ? { decision: "deny", reason: message } : { decision: "allow" })
    );
    process.exit(0);
  }
  // claude / codex
  if (block) {
    process.stderr.write(message + "\n");
    process.exit(2);
  }
  if (warn && message) {
    process.stdout.write(JSON.stringify({ systemMessage: message }));
  }
  process.exit(0);
}

function run(evaluate) {
  const raw = readStdin();
  let data = {};
  try {
    data = raw ? JSON.parse(raw) : {};
  } catch {
    data = {};
  }
  const host = detectHost(data);
  let verdict;
  try {
    verdict = evaluate(normalize(host, raw), host);
  } catch (e) {
    // Fail-safe: an internal error in gate logic must never block real work.
    verdict = { block: false };
  }
  emit(host, verdict);
}

module.exports = { readStdin, detectHost, normalize, emit, run };
