"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// `npx soloship upgrade`. Ported from buildPreToolUseScript (src/hooks.ts) +
// the Cursor RULES array (src/hooks.ts) — same validated patterns, one copy.
const { run } = require("./_shared.cjs");

const RULES = [
  [new RegExp("\\brm\\s+(?:-\\S+\\s+)+[\"']?(?:~|\\$HOME|/Users|/home|/)(?:[\\s/*\"']|$)"), "BLOCKED: dangerous rm -rf targeting a home or root directory."],
  [new RegExp("(?:cat|echo|printf|>)\\s*[^|]*\\.env(?:\\s|$|\\.)"), "BLOCKED: direct .env modification. Secrets are edited by hand, never by an agent."],
  [new RegExp("git\\s+push\\b(?=[^\\n]*(?:--force|\\s-f(?:\\s|$)))(?=[^\\n]*\\b(?:main|master)\\b)"), "BLOCKED: force push to main/master rewrites shared history."],
  [new RegExp("(?:ANTHROPIC|OPENAI|STRIPE|FIREBASE|GEMINI|CURSOR)_[A-Z_]*KEY\\s*=\\s*[\"'][a-zA-Z0-9_\\-]{20,}[\"']"), "BLOCKED: possible hardcoded API key. Use an env var or the platform secret store."],
];

const DEPLOY_RE = new RegExp("(?:npm\\s+run\\s+deploy|wrangler\\s+deploy|fly\\s+deploy|vercel\\s+--prod|netlify\\s+deploy[^\\n]*--prod)");

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!cmd) return { block: false };

  for (const [re, reason] of RULES) {
    if (re.test(cmd)) return { block: true, message: reason };
  }

  if (DEPLOY_RE.test(cmd)) {
    try {
      const branch = require("child_process")
        .execSync("git branch --show-current 2>/dev/null", { encoding: "utf8" })
        .trim();
      if (branch && branch !== "main" && branch !== "master") {
        return {
          block: true,
          message:
            "BLOCKED: production deploys must run from the default branch. You are on '" +
            branch +
            "'. Merge to main first, then deploy from there.",
        };
      }
    } catch {
      // No git, or git failed: nothing to assert.
    }
  }

  return { block: false };
}

run(evaluate);
