"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// `npx soloship upgrade`. Ported from buildPlanTruthGateScript (src/hooks.ts).
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { run } = require("./_shared.cjs");

const PLANS_DIR = "docs/plans";
const PLAN_STATUS_ACK = ".ai/.plan-status-ack";

function git(cmd) {
  try {
    return execSync(cmd + " 2>/dev/null", { encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!/git\s+commit/.test(cmd)) return { block: false };
  if (fs.existsSync(PLAN_STATUS_ACK)) return { block: false };
  if (!fs.existsSync(PLANS_DIR)) return { block: false };

  const staged = git("git diff --cached --name-only").split("\n").filter(Boolean);
  if (!staged.length) return { block: false };
  if (!staged.some((f) => !f.startsWith("docs/"))) return { block: false };

  const branch = git("git branch --show-current");
  if (!branch) return { block: false };

  let plan = null;
  const commonDir = git("git rev-parse --git-common-dir");
  if (commonDir) {
    try {
      const coordClaims = path.join(fs.realpathSync(commonDir), "soloship", "claims");
      if (fs.existsSync(coordClaims)) {
        for (const c of fs.readdirSync(coordClaims)) {
          if (!c.endsWith(".json")) continue;
          const full = path.join(coordClaims, c);
          let body = "";
          try {
            body = fs.readFileSync(full, "utf8");
          } catch {
            continue;
          }
          if (body.includes(`"branch":"${branch}"`)) {
            const cand = path.join(PLANS_DIR, c.replace(/\.json$/, ""));
            if (fs.existsSync(cand)) {
              plan = cand;
              break;
            }
          }
        }
      }
    } catch {
      // ignore
    }
  }
  if (!plan) {
    const slug = branch.replace(/^(feat|fix|chore|refactor)\//, "");
    for (const f of fs.readdirSync(PLANS_DIR)) {
      if (f === "README.md" || !f.endsWith(".md")) continue;
      if (f.includes(slug)) {
        plan = path.join(PLANS_DIR, f);
        break;
      }
    }
  }
  if (!plan) return { block: false };

  const body = fs.readFileSync(plan, "utf8");
  const m = body.match(/^status:\s*"?([^"\n]*?)"?\s*$/m);
  let status = (m ? m[1] : "").trim().toLowerCase();
  if (status === "not started" || status === "not-started") status = "planned";

  if (status === "planned") {
    const today = new Date().toISOString().slice(0, 10);
    return {
      block: true,
      message:
        `BLOCKED by plan-truth-gate: you are committing CODE on branch "${branch}", but its plan (${plan}) still says "status: planned" — i.e. the plan claims this work has not started. That is exactly how plans come to lie about themselves: the work ships, the status never moves, and the next agent reads "not started" and builds it a second time.\n\n` +
        `FIX (5 seconds): set the plan frontmatter to\n  status: in-progress\n  claimed_by: <this session>\n  branch: ${branch}\n  updated: ${today}\nthen re-run the commit. Flip it to "done" when the work merges.\n\n` +
        `Escape hatch (requires a real reason): mkdir -p .ai && echo "why a lying plan is correct here" > ${PLAN_STATUS_ACK}`,
    };
  }

  return { block: false };
}

run(evaluate);
