"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// `npx soloship upgrade`. Ported from buildPlanMergeGateScript (src/hooks.ts).
const fs = require("fs");
const { run } = require("./_shared.cjs");

const PLANS_DIR = "docs/plans";
const PLAN_STATUS_ACK = ".ai/.plan-status-ack";
const OPEN_STATUSES = new Set(["planned","in-progress"]);

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!/git\s+merge/.test(cmd)) return { block: false };
  if (fs.existsSync(PLAN_STATUS_ACK)) return { block: false };
  if (!fs.existsSync(PLANS_DIR)) return { block: false };

  const today = new Date().toISOString().slice(0, 10);

  for (const f of fs.readdirSync(PLANS_DIR)) {
    if (f === "README.md" || !f.endsWith(".md")) continue;
    const full = `${PLANS_DIR}/${f}`;
    let body;
    try {
      body = fs.readFileSync(full, "utf8");
    } catch {
      continue;
    }
    const m = body.match(/^status:\s*"?([^"\n]*?)"?\s*$/m);
    let status = (m ? m[1] : "").trim().toLowerCase();
    if (status === "not started" || status === "not-started") status = "planned";
    if (status === "active") status = "in-progress";
    if (!OPEN_STATUSES.has(status)) continue;

    const bm = body.match(/^branch:\s*"?(\S+)"?\s*$/m);
    const pbranch = bm ? bm[1] : "";
    if (!pbranch) continue;
    if (!cmd.includes(pbranch)) continue;

    return {
      block: true,
      message:
        `BLOCKED by plan-merge-gate: you are merging branch "${pbranch}", but its plan (${full}) still says "status: ${status}". After this merge the work is live — and if the status never moves, the plan will claim forever that this work was never finished. That is the exact defect this gate exists to prevent.\n\n` +
        `FIX: set the plan frontmatter to\n  status: done\n  progress: "<total>/<total>"\n  updated: ${today}\nremove the claimed_by line, then re-run the merge.\n\n` +
        `If the work is genuinely NOT complete and you are merging partial work on purpose, set an honest status instead (blocked / superseded) and say so in the plan.\n\n` +
        `Escape hatch (requires a real reason): mkdir -p .ai && echo "reason" > ${PLAN_STATUS_ACK}`,
    };
  }

  return { block: false };
}

run(evaluate);
