"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// `npx soloship upgrade`. Ported from buildRecurrenceGateScript (src/hooks.ts).
// Spec: docs/plans/2026-05-16-recurrence-gate.md.
const fs = require("fs");
const { execSync } = require("child_process");
const { run } = require("./_shared.cjs");

const STOPWORDS = new Set([
  "the","and","for","with","that","this","from","into","has","have","not","are","was","were",
  "feat","fix","docs","chore","refactor",
]);

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!/git\s+commit/.test(cmd)) return { block: false };

  const L = ".ai/learnings.jsonl";
  if (!fs.existsSync(L)) return { block: false };

  let staged;
  try {
    staged = execSync("git diff --cached --name-only 2>/dev/null", { encoding: "utf8" }).toLowerCase();
  } catch {
    staged = "";
  }
  if (!staged.trim()) return { block: false };

  // Heredoc bodies (CE/soloship use them heavily) cannot be token-parsed from
  // the command string — fall back to file-overlap-only and WARN instead of
  // block at the 1-match tier.
  let degraded = false;
  let msg = "";
  if (/<<-?\s*['"]?[A-Za-z_]+/.test(cmd)) {
    degraded = true;
  } else {
    const m = cmd.match(/-m\s+"([^"]*)"/) || cmd.match(/-m\s+'([^']*)'/);
    if (m) msg = m[1];
    else degraded = true;
  }
  const msgTokens = new Set(
    msg.toLowerCase().replace(/[^a-z0-9]+/g, " ").split(" ").filter((t) => t.length > 3 && !STOPWORDS.has(t))
  );

  const ack = fs.existsSync(".ai/.recurrence-ack");
  const RL = ".ai/.recurrence-log";

  const lines = fs.readFileSync(L, "utf8").split("\n").filter(Boolean);
  let matched = 0;
  let hist = "";
  const mkeys = [];

  for (const line of lines) {
    if (!line.includes("key") || !line.includes("components")) continue;
    let rec;
    try {
      rec = JSON.parse(line);
    } catch {
      continue;
    }
    const comps = Array.isArray(rec.components) ? rec.components.map((c) => String(c).toLowerCase()) : [];
    if (!comps.length) continue;

    let fileHit = false;
    for (const c of comps) {
      if (c.length <= 2) continue;
      if (staged.includes(c)) {
        fileHit = true;
        break;
      }
      for (const ct of c.split(/[^a-z0-9]+/).filter(Boolean)) {
        if (ct.length <= 3) continue;
        if (staged.includes(ct)) {
          fileHit = true;
          break;
        }
      }
      if (fileHit) break;
    }
    if (!fileHit) continue;

    let tokHit = degraded;
    if (!degraded) {
      const ki = new Set(
        `${rec.key || ""} ${rec.insight || ""}`.toLowerCase().replace(/[^a-z0-9]+/g, " ").split(" ").filter(Boolean)
      );
      for (const t of msgTokens) {
        if (ki.has(t)) {
          tokHit = true;
          break;
        }
      }
    }
    if (!tokHit) continue;

    matched++;
    hist += ` | ${rec.date || ""}  ${rec.key || ""}  ->  ${rec.solution || ""}`;
    if (rec.key) mkeys.push(rec.key);
  }

  if (matched === 0) return { block: false };

  let prior = 0;
  if (fs.existsSync(RL)) {
    const rl = fs.readFileSync(RL, "utf8");
    for (const k of mkeys) {
      prior += rl.split(`|${k}|`).length - 1;
    }
  }
  const tier = matched + prior;

  if (ack) {
    return {
      block: false,
      warn: true,
      message: `recurrence-gate: .ai/.recurrence-ack present — allowing a commit that matches a recorded failure class (${hist} ). The ack records that a patch is justified THIS time; writing it without a real reason defeats the gate.`,
    };
  }

  if (tier >= 2) {
    return {
      block: true,
      message: `BLOCKED by recurrence-gate — Hard stop (this failure class has recurred ${tier} times):${hist}\nA repeat patch is not the fix. Escalate to a MECHANICAL fix (hook, test, or structural change) so it cannot recur. If a patch is genuinely correct this time, record why: mkdir -p .ai && echo "<reason> ($(date +%F))" >> .ai/.recurrence-ack then re-commit.`,
    };
  }

  if (degraded) {
    return {
      block: false,
      warn: true,
      message: `recurrence-gate WARNING (degraded match — heredoc/unparseable commit message, file-overlap only, not blocking on the weaker signal): this commit touches a recorded failure class:${hist} . If it is the same failure, escalate to a mechanical fix instead of re-patching.`,
    };
  }

  return {
    block: true,
    message: `BLOCKED by recurrence-gate — first recurrence:${hist}\nThis failure class was already addressed (see the solution path above). A second patch is not allowed. Either escalate to a mechanical fix (hook/test/structural change) so it cannot recur, or, if a patch is genuinely correct this time, record why: mkdir -p .ai && echo "<reason> ($(date +%F))" >> .ai/.recurrence-ack then re-commit. Writing that file without a real reason removes the protection this gate provides — if the gate seems wrong, surface that to the user instead.`,
  };
}

run(evaluate);
