import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { Script } from "node:vm";
import {
  PLANS_DIR,
  PLAN_STATUS_ACK,
  BILLING_ACK,
  PLAN_STATUSES,
  PLAN_STATUSES_OPEN,
  DEPLOY_LOCK_STALE_MIN,
  CURSOR_DANGEROUS_RM_RE,
  CURSOR_ENV_WRITE_RE,
  CURSOR_FORCE_PUSH_RE,
  CURSOR_API_KEY_RE,
  CURSOR_DEPLOY_RE,
} from "./hooks.js";

// One committed .cjs gate file per gate, shared across every hook-capable
// host (Claude Code, Cursor, Codex, Antigravity). Phase 1 of
// docs/plans/2026-08-27-one-source-of-truth-across-agent-hosts.md.
//
// Why this file exists instead of extending the bash builders in hooks.ts:
// the bash generation in hooks.ts was fixed 2026-08-27 to read stdin instead
// of a nonexistent env var, and that fix surfaced two MORE bugs on top of the
// original one — a boundary regex that could never match before a JSON
// closing quote, and a quote-extraction regex that could never match a
// JSON-escaped `\"`. Both were bash hand-parsing raw JSON with grep/sed. A
// real JSON.parse (available for free — every host that runs hooks also has
// Node, since Soloship itself installs via npx) removes that entire bug
// class rather than patching around it a third time. It also removes the
// documented macOS-grep-has-no-\b pitfall (src/AGENTS.md) since these use
// real JS RegExp, which supports \b everywhere.
//
// Each generated .cjs is self-contained (requires only Node builtins) and
// auto-detects which host invoked it from the shape of the stdin payload —
// no argv, no per-host copies, no `--host` flag to keep in sync with the
// adapter config:
//   - Claude Code and Codex CLI share byte-identical PreToolUse contracts
//     (verified live against both vendors' docs, 2026-08-27: stdin JSON with
//     {hook_event_name, tool_name, tool_input, session_id, cwd}; block via
//     exit 2 + stderr, or exit 0 + {systemMessage} JSON to warn without
//     blocking) — one code path covers both, labeled "claude" internally.
//   - Cursor's beforeShellExecution delivers a bare {command, cwd, sandbox}
//     with no tool_input wrapper — that shape alone is the signal.
//   - Antigravity wraps everything in {toolCall: {name, args}}.
// An unrecognized shape falls through to the Claude/Codex contract (the
// widest-adopted one) rather than silently no-op'ing, so a host this file
// hasn't been taught about yet still gets exit-2 blocking instead of nothing.
//
// Committed path: `scripts/soloship-hooks/`, NOT `.soloship/hooks/`. The
// first attempt used `.soloship/hooks/`, reasoning that `.soloship/.gitignore`
// only excludes `.last-update-check` (see scaffold.ts) — true, but
// irrelevant: Soloship's own repo (which dogfoods itself) has a BLANKET
// `.soloship/` line in its ROOT .gitignore, predating this plan, and git
// cannot re-include anything under a directory a parent pattern already
// excludes (`!.soloship/hooks/` is a no-op once `.soloship/` itself matches
// — git never even descends into it). Any project with a similar root rule
// would silently get gate files that install but never reach the clone —
// the exact "gate that never runs" failure Phase 0 exists to prevent, just
// moved one layer up. Editing an arbitrary project's existing .gitignore
// lines to fix this is the fragile move; a sibling directory nothing has a
// reason to already exclude is not. `scripts/` is a plain, commonly-tracked
// directory (this repo already commits `scripts/release.js`).
//
// writeCommittedGateFiles() below still defends against the general failure
// class (some OTHER project-specific ignore rule) by asking git itself
// whether each file it just wrote is ignored, and throwing loudly if so —
// same precedent as the Cursor installer's dead-path throw.
export const GATE_DIRNAME = "soloship-hooks";
export const GATE_BASE_DIR = "scripts";

// Gate names double as filenames (`<name>.cjs`) and as the doctor/report
// labels — keep them kebab-case and stable; renaming one orphans the file it
// used to write on every project that already ran an older Soloship.
export const GATE_NAMES = [
  "command-safety",
  "billing-confirmation",
  "recurrence",
  "deploy-freshness",
  "deploy-discipline",
  "plan-truth",
  "plan-merge",
  "plan-namespace",
] as const;

export type GateName = (typeof GATE_NAMES)[number];

function sharedHelperSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Shared normalize/detect/emit helpers every gate
// file in this directory requires. See src/committed-gates.ts in the
// Soloship repo for the source of truth and full rationale.

const fs = require("fs");

function readStdin() {
  try {
    return fs.readFileSync(0, "utf8");
  } catch {
    return "";
  }
}

function detectHost(data) {
  if (data && typeof data === "object" && data.toolCall && typeof data.toolCall === "object") {
    return "antigravity";
  }
  if (data && typeof data === "object" && typeof data.command === "string" && data.tool_input === undefined) {
    return "cursor";
  }
  return "claude"; // covers Claude Code + Codex CLI (identical contract), and any unrecognized shape
}

function normalize(host, raw) {
  let data = {};
  try {
    data = raw ? JSON.parse(raw) : {};
  } catch {
    data = {};
  }
  if (host === "cursor") {
    return {
      toolInput: {
        command: data.command || "",
        filePath: data.file_path || data.filePath || "",
        content: data.content ?? "",
      },
      cwd: (data.workspace_roots && data.workspace_roots[0]) || data.cwd || process.cwd(),
      sessionId: data.conversation_id || "",
    };
  }
  if (host === "antigravity") {
    const call = data.toolCall || {};
    const args = call.args || {};
    return {
      toolInput: {
        command: args.CommandLine || "",
        filePath: args.TargetFile || args.AbsolutePath || "",
        content: args.CodeContent || args.ReplacementContent || "",
      },
      cwd: data.cwd || process.cwd(),
      sessionId: data.session_id || "",
    };
  }
  // claude / codex
  const ti = data.tool_input || {};
  return {
    toolInput: {
      command: ti.command || "",
      filePath: ti.file_path || "",
      content: ti.content ?? ti.file_text ?? ti.new_string ?? "",
    },
    cwd: data.cwd || process.cwd(),
    sessionId: data.session_id || "",
  };
}

// verdict: {block: boolean, message?: string, warn?: boolean}
// warn (without block) surfaces \`message\` as a non-blocking systemMessage on
// hosts that support it (Claude, Codex); Cursor and Antigravity have no
// non-blocking-message channel in their current hook contracts, so warn is a
// silent no-op there rather than a fabricated block.
function emit(host, verdict) {
  const block = !!(verdict && verdict.block);
  const warn = !!(verdict && verdict.warn);
  const message = (verdict && verdict.message) || "";
  if (host === "cursor") {
    process.stdout.write(
      JSON.stringify(
        block
          ? { permission: "deny", user_message: message, agent_message: message }
          : { permission: "allow" }
      )
    );
    process.exit(0);
  }
  if (host === "antigravity") {
    process.stdout.write(
      JSON.stringify(block ? { decision: "deny", reason: message } : { decision: "allow" })
    );
    process.exit(0);
  }
  // claude / codex
  if (block) {
    process.stderr.write(message + "\\n");
    process.exit(2);
  }
  if (warn && message) {
    process.stdout.write(JSON.stringify({ systemMessage: message }));
  }
  process.exit(0);
}

function run(evaluate) {
  const raw = readStdin();
  let data = {};
  try {
    data = raw ? JSON.parse(raw) : {};
  } catch {
    data = {};
  }
  const host = detectHost(data);
  let verdict;
  try {
    verdict = evaluate(normalize(host, raw), host);
  } catch (e) {
    // Fail-safe: an internal error in gate logic must never block real work.
    verdict = { block: false };
  }
  emit(host, verdict);
}

module.exports = { readStdin, detectHost, normalize, emit, run };
`;
}

function commandSafetySource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildPreToolUseScript (src/hooks.ts) +
// the Cursor RULES array (src/hooks.ts) — same validated patterns, one copy.
const { run } = require("./_shared.cjs");

const RULES = [
  [new RegExp(${JSON.stringify(CURSOR_DANGEROUS_RM_RE)}), "BLOCKED: dangerous rm -rf targeting a home or root directory."],
  [new RegExp(${JSON.stringify(CURSOR_ENV_WRITE_RE)}), "BLOCKED: direct .env modification. Secrets are edited by hand, never by an agent."],
  [new RegExp(${JSON.stringify(CURSOR_FORCE_PUSH_RE)}), "BLOCKED: force push to main/master rewrites shared history."],
  [new RegExp(${JSON.stringify(CURSOR_API_KEY_RE)}), "BLOCKED: possible hardcoded API key. Use an env var or the platform secret store."],
];

const DEPLOY_RE = new RegExp(${JSON.stringify(CURSOR_DEPLOY_RE)});

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!cmd) return { block: false };

  for (const [re, reason] of RULES) {
    if (re.test(cmd)) return { block: true, message: reason };
  }

  if (DEPLOY_RE.test(cmd)) {
    try {
      const branch = require("child_process")
        .execSync("git branch --show-current 2>/dev/null", { encoding: "utf8" })
        .trim();
      if (branch && branch !== "main" && branch !== "master") {
        return {
          block: true,
          message:
            "BLOCKED: production deploys must run from the default branch. You are on '" +
            branch +
            "'. Merge to main first, then deploy from there.",
        };
      }
    } catch {
      // No git, or git failed: nothing to assert.
    }
  }

  return { block: false };
}

run(evaluate);
`;
}

function billingConfirmationSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildBillingGateScript (src/hooks.ts).
// See .claude/rules/billing-confirmation-gate.md for the rule this enforces.
const fs = require("fs");
const { run } = require("./_shared.cjs");

const TARGET_RE = /(billing|credit|invoice|subscription|proration|payout|ledger|stripe|rerun[-_]?window|grace[-_]?period|trial[-_]?(length|end|days))/i;
const CONTENT_RE = /(credit[_-]?balance|creditBalance|credits?\\s*[-+]?=|rerun[_-]?window|rerunWindow|grace[_-]?period|trial[_-]?(ends?|end_at|length|days)|amount[_-]?due|amountDue|invoice|subscription|proration|refund|stripe\\.[a-z]|charge[A-Z_])/;

function evaluate(n) {
  if (fs.existsSync(${JSON.stringify(BILLING_ACK)})) return { block: false };

  const filePath = n.toolInput.filePath || "";
  const content = n.toolInput.content || "";
  const pathHit = TARGET_RE.test(filePath);
  const contentHit = CONTENT_RE.test(content);
  if (!pathHit && !contentHit) return { block: false };

  const why = pathHit ? filePath.match(TARGET_RE)[0] : content.match(CONTENT_RE)[0];
  return {
    block: true,
    message:
      "BLOCKED by billing-confirmation-gate: this edit touches billing / credit / rerun-window state (matched: " + why + "). " +
      "Per the billing-confirmation-gate rule, you must FIRST confirm the data-model semantics with the user — " +
      "unit & sign (cents vs dollars, balance vs delta), idempotency (what a double-run does), the window boundary " +
      "(inclusive/exclusive, timezone), and backfill scope (which rows, before/after counts). Do NOT write this code " +
      "until the user confirms. After they confirm, record it: mkdir -p .ai && echo \\"confirmed: <what> ($(date +%Y-%m-%d))\\" " +
      "> .ai/.billing-ack — then this gate stands down. Creating that file without an actual confirmation removes the " +
      "protection this gate provides — if the gate seems wrong, surface that to the user instead.",
  };
}

run(evaluate);
`;
}

function recurrenceSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildRecurrenceGateScript (src/hooks.ts).
// Spec: docs/plans/2026-05-16-recurrence-gate.md.
const fs = require("fs");
const { execSync } = require("child_process");
const { run } = require("./_shared.cjs");

const STOPWORDS = new Set([
  "the","and","for","with","that","this","from","into","has","have","not","are","was","were",
  "feat","fix","docs","chore","refactor",
]);

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!/git\\s+commit/.test(cmd)) return { block: false };

  const L = ".ai/learnings.jsonl";
  if (!fs.existsSync(L)) return { block: false };

  let staged;
  try {
    staged = execSync("git diff --cached --name-only 2>/dev/null", { encoding: "utf8" }).toLowerCase();
  } catch {
    staged = "";
  }
  if (!staged.trim()) return { block: false };

  // Heredoc bodies (CE/soloship use them heavily) cannot be token-parsed from
  // the command string — fall back to file-overlap-only and WARN instead of
  // block at the 1-match tier.
  let degraded = false;
  let msg = "";
  if (/<<-?\\s*['"]?[A-Za-z_]+/.test(cmd)) {
    degraded = true;
  } else {
    const m = cmd.match(/-m\\s+"([^"]*)"/) || cmd.match(/-m\\s+'([^']*)'/);
    if (m) msg = m[1];
    else degraded = true;
  }
  const msgTokens = new Set(
    msg.toLowerCase().replace(/[^a-z0-9]+/g, " ").split(" ").filter((t) => t.length > 3 && !STOPWORDS.has(t))
  );

  const ack = fs.existsSync(".ai/.recurrence-ack");
  const RL = ".ai/.recurrence-log";

  const lines = fs.readFileSync(L, "utf8").split("\\n").filter(Boolean);
  let matched = 0;
  let hist = "";
  const mkeys = [];

  for (const line of lines) {
    if (!line.includes("key") || !line.includes("components")) continue;
    let rec;
    try {
      rec = JSON.parse(line);
    } catch {
      continue;
    }
    const comps = Array.isArray(rec.components) ? rec.components.map((c) => String(c).toLowerCase()) : [];
    if (!comps.length) continue;

    let fileHit = false;
    for (const c of comps) {
      if (c.length <= 2) continue;
      if (staged.includes(c)) {
        fileHit = true;
        break;
      }
      for (const ct of c.split(/[^a-z0-9]+/).filter(Boolean)) {
        if (ct.length <= 3) continue;
        if (staged.includes(ct)) {
          fileHit = true;
          break;
        }
      }
      if (fileHit) break;
    }
    if (!fileHit) continue;

    let tokHit = degraded;
    if (!degraded) {
      const ki = new Set(
        \`\${rec.key || ""} \${rec.insight || ""}\`.toLowerCase().replace(/[^a-z0-9]+/g, " ").split(" ").filter(Boolean)
      );
      for (const t of msgTokens) {
        if (ki.has(t)) {
          tokHit = true;
          break;
        }
      }
    }
    if (!tokHit) continue;

    matched++;
    hist += \` | \${rec.date || ""}  \${rec.key || ""}  ->  \${rec.solution || ""}\`;
    if (rec.key) mkeys.push(rec.key);
  }

  if (matched === 0) return { block: false };

  let prior = 0;
  if (fs.existsSync(RL)) {
    const rl = fs.readFileSync(RL, "utf8");
    for (const k of mkeys) {
      prior += rl.split(\`|\${k}|\`).length - 1;
    }
  }
  const tier = matched + prior;

  if (ack) {
    return {
      block: false,
      warn: true,
      message: \`recurrence-gate: .ai/.recurrence-ack present — allowing a commit that matches a recorded failure class (\${hist} ). The ack records that a patch is justified THIS time; writing it without a real reason defeats the gate.\`,
    };
  }

  if (tier >= 2) {
    return {
      block: true,
      message: \`BLOCKED by recurrence-gate — Hard stop (this failure class has recurred \${tier} times):\${hist}\\nA repeat patch is not the fix. Escalate to a MECHANICAL fix (hook, test, or structural change) so it cannot recur. If a patch is genuinely correct this time, record why: mkdir -p .ai && echo "<reason> ($(date +%F))" >> .ai/.recurrence-ack then re-commit.\`,
    };
  }

  if (degraded) {
    return {
      block: false,
      warn: true,
      message: \`recurrence-gate WARNING (degraded match — heredoc/unparseable commit message, file-overlap only, not blocking on the weaker signal): this commit touches a recorded failure class:\${hist} . If it is the same failure, escalate to a mechanical fix instead of re-patching.\`,
    };
  }

  return {
    block: true,
    message: \`BLOCKED by recurrence-gate — first recurrence:\${hist}\\nThis failure class was already addressed (see the solution path above). A second patch is not allowed. Either escalate to a mechanical fix (hook/test/structural change) so it cannot recur, or, if a patch is genuinely correct this time, record why: mkdir -p .ai && echo "<reason> ($(date +%F))" >> .ai/.recurrence-ack then re-commit. Writing that file without a real reason removes the protection this gate provides — if the gate seems wrong, surface that to the user instead.\`,
  };
}

run(evaluate);
`;
}

function deployFreshnessSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildDeployFreshnessScript (src/hooks.ts).
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { run } = require("./_shared.cjs");

const DEPLOY_RE = /(firebase\\s+deploy|wrangler\\s+(pages\\s+deploy|deploy)|netlify\\s+deploy|fly\\s+deploy|vercel(\\s|$)|(npm|pnpm|yarn|bun)(\\s+run)?\\s+deploy)/;
const REMOTE_BUILD_RE = /vercel(\\s|$)|netlify\\s+deploy|fly\\s+deploy/;
const BUILD_CMD_RE = /(npm|pnpm|yarn|bun)(\\s+run)?\\s+build|vite\\s+build|next\\s+build|(^|[\\s;&|])tsc(\\s|$)/;
const DEPLOY_SCRIPT_RE = /(npm|pnpm|yarn|bun)(\\s+run)?\\s+deploy/;
const ARTIFACT_DIRS = ["dist", "build", ".next", "out", ".output/public", "public/build"];
const SOURCE_EXT_RE = /\\.(ts|tsx|js|jsx|mjs|cjs|css|scss|html|vue|svelte|astro)$/;
const TEST_FILE_RE = /\\.(config|test|spec)\\.(js|ts|mjs|cjs|jsx|tsx)$/;
const PRUNE_DIRS = new Set(["node_modules", ".git", "dist", "build", ".next", "out", ".output", ".worktrees", ".ai"]);

function findArtifactDir() {
  for (const d of ARTIFACT_DIRS) {
    if (fs.existsSync(d) && fs.statSync(d).isDirectory()) return d;
  }
  return null;
}

function newestMtime(dir) {
  let newest = 0;
  let stack = [dir];
  while (stack.length) {
    const cur = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(cur, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      const full = path.join(cur, e.name);
      if (e.isDirectory()) stack.push(full);
      else {
        try {
          const mt = fs.statSync(full).mtimeMs;
          if (mt > newest) newest = mt;
        } catch {
          // ignore
        }
      }
    }
  }
  return newest;
}

function findStaleSource(artifactDir, newestArtifactMtime) {
  const stale = [];
  let stack = ["."];
  while (stack.length && stale.length < 3) {
    const cur = stack.pop();
    let entries;
    try {
      entries = fs.readdirSync(cur, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      if (e.name === artifactDir || PRUNE_DIRS.has(e.name)) continue;
      const full = path.join(cur, e.name);
      if (e.isDirectory()) {
        stack.push(full);
      } else if (SOURCE_EXT_RE.test(e.name) && !TEST_FILE_RE.test(e.name)) {
        try {
          if (fs.statSync(full).mtimeMs > newestArtifactMtime) stale.push(full);
        } catch {
          // ignore
        }
      }
      if (stale.length >= 3) break;
    }
  }
  return stale;
}

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!DEPLOY_RE.test(cmd)) return { block: false };

  let warnMessage = "";

  // D1 unapplied-migration warning (warn only; cannot know remote state).
  if (
    /wrangler\\s+(pages\\s+deploy|deploy)/.test(cmd) &&
    !/d1\\s+migrations\\s+apply/.test(cmd) &&
    fs.existsSync("wrangler.toml") &&
    /\\[\\[d1_databases\\]\\]/.test(fs.readFileSync("wrangler.toml", "utf8")) &&
    fs.existsSync("migrations") &&
    fs.readdirSync("migrations").some((f) => f.endsWith(".sql"))
  ) {
    warnMessage =
      "Deploy targets a D1-backed Worker. Schema migrations do NOT ship with a wrangler deploy — confirm " +
      "wrangler d1 migrations apply has been run for any new files in migrations/, or the deployed code will hit a stale schema.";
  }

  if (REMOTE_BUILD_RE.test(cmd)) {
    return warnMessage ? { block: false, warn: true, message: warnMessage } : { block: false };
  }

  const artifactDir = findArtifactDir();
  if (!artifactDir) return warnMessage ? { block: false, warn: true, message: warnMessage } : { block: false };

  if (!fs.existsSync("package.json") || !/"build"\\s*:/.test(fs.readFileSync("package.json", "utf8"))) {
    return warnMessage ? { block: false, warn: true, message: warnMessage } : { block: false };
  }

  let runsBuild = BUILD_CMD_RE.test(cmd);
  if (!runsBuild && DEPLOY_SCRIPT_RE.test(cmd)) {
    try {
      const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
      const deployScript = (pkg.scripts && pkg.scripts.deploy) || "";
      if (/build|vite|next build|tsc/.test(deployScript)) runsBuild = true;
    } catch {
      // ignore
    }
  }
  if (runsBuild) return warnMessage ? { block: false, warn: true, message: warnMessage } : { block: false };

  const newest = newestMtime(artifactDir);
  if (!newest) return warnMessage ? { block: false, warn: true, message: warnMessage } : { block: false };

  const stale = findStaleSource(artifactDir, newest);
  if (stale.length) {
    return {
      block: true,
      message: \`BLOCKED: build artifact (\${artifactDir}/) is older than your source (e.g. \${stale[0]}). This deploy command does not run a build, so it would ship a STALE bundle and your fix would not reach production. Run your build (npm run build) first, then deploy.\`,
    };
  }

  return warnMessage ? { block: false, warn: true, message: warnMessage } : { block: false };
}

run(evaluate);
`;
}

function deployDisciplineSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildDeployDisciplineScript (src/hooks.ts).
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { run } = require("./_shared.cjs");

const DEPLOY_RE = /(firebase\\s+deploy|wrangler\\s+(pages\\s+deploy|deploy)|netlify\\s+deploy|fly\\s+deploy|vercel(\\s|$)|(npm|pnpm|yarn|bun)(\\s+run)?\\s+deploy)/;
const DEPLOY_LOCK_STALE_MIN = ${DEPLOY_LOCK_STALE_MIN};

function git(cmd) {
  try {
    return execSync(cmd + " 2>/dev/null", { encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!DEPLOY_RE.test(cmd)) return { block: false };

  // Preview/channel deploys are exempt — worktree sessions must keep
  // deploying previews for browser QA.
  if (/wrangler\\s+pages\\s+deploy/.test(cmd) && /--branch/.test(cmd)) return { block: false };
  if (/firebase\\s+hosting:channel:deploy/.test(cmd)) return { block: false };
  if (/vercel(\\s|$)/.test(cmd) && !/--prod/.test(cmd)) return { block: false };
  if (/netlify\\s+deploy/.test(cmd) && !/--prod/.test(cmd)) return { block: false };

  const gitDirRaw = git("git rev-parse --git-dir");
  if (!gitDirRaw) return { block: false };
  let gd, gcd;
  try {
    gd = fs.realpathSync(gitDirRaw);
    gcd = fs.realpathSync(git("git rev-parse --git-common-dir"));
  } catch {
    return { block: false };
  }
  if (!gcd) return { block: false };

  if (gd !== gcd) {
    return {
      block: true,
      message:
        "BLOCKED by deploy-from-main-only: this is a PRODUCTION deploy from a git worktree. Production must be " +
        "deployed from the main checkout on the default branch, after merging — otherwise what is live diverges " +
        "from main and the next deploy from main silently rolls this work back. Merge to the default branch first " +
        "(see /soloship:finish), then deploy from the main checkout. Preview deploys (wrangler pages deploy " +
        "--branch, vercel without --prod, firebase hosting:channel:deploy) remain allowed from worktrees.",
    };
  }

  const br = git("git branch --show-current");
  let def = git("git symbolic-ref --short refs/remotes/origin/HEAD").replace(/^origin\\//, "");
  if (!def) {
    if (git("git rev-parse --verify -q origin/main")) def = "main";
    else if (git("git rev-parse --verify -q origin/master")) def = "master";
    else if (git("git rev-parse --verify -q main")) def = "main";
    else if (git("git rev-parse --verify -q master")) def = "master";
  }
  if (def && br && br !== def) {
    return {
      block: true,
      message: \`BLOCKED by deploy-from-main-only: this is a PRODUCTION deploy from branch \${br}, not the default branch (\${def}). Merge to \${def} first, then deploy from a clean, synced \${def} checkout. Preview deploys remain allowed from feature branches.\`,
    };
  }

  const dirty = git("git status --porcelain");
  if (dirty) {
    return {
      block: true,
      message:
        "BLOCKED by deploy-from-main-only: the working tree has uncommitted changes. A production deploy must " +
        "ship exactly a commit on the default branch — commit (or stash) everything first, so the prod tag can " +
        "truthfully mark what is live.",
    };
  }

  const lock = path.join(gcd, "soloship", "deploy.lock");
  if (fs.existsSync(lock)) {
    const sid = n.sessionId || "pid-unknown";
    let lsid = "";
    try {
      const m = fs.readFileSync(lock, "utf8").match(/"session_id":"([^"]*)"/);
      lsid = m ? m[1] : "";
    } catch {
      lsid = "";
    }
    if (lsid && lsid !== sid) {
      let ageMin = 0;
      try {
        ageMin = Math.floor((Date.now() - fs.statSync(lock).mtimeMs) / 60000);
      } catch {
        ageMin = 0;
      }
      if (ageMin < DEPLOY_LOCK_STALE_MIN) {
        return {
          block: true,
          message: \`BLOCKED by deploy-from-main-only: another session (id \${lsid}) holds the deploy lock (refreshed \${ageMin} min ago) — a deploy is already in progress. Wait for it to finish, or ask the user how to proceed. A lock is presumed stale only after \${DEPLOY_LOCK_STALE_MIN} min, and even then only the user may clear it: rm "\${lock}"\`,
        };
      }
    }
  }

  return { block: false };
}

run(evaluate);
`;
}

function planTruthSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildPlanTruthGateScript (src/hooks.ts).
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");
const { run } = require("./_shared.cjs");

const PLANS_DIR = ${JSON.stringify(PLANS_DIR)};
const PLAN_STATUS_ACK = ${JSON.stringify(PLAN_STATUS_ACK)};

function git(cmd) {
  try {
    return execSync(cmd + " 2>/dev/null", { encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!/git\\s+commit/.test(cmd)) return { block: false };
  if (fs.existsSync(PLAN_STATUS_ACK)) return { block: false };
  if (!fs.existsSync(PLANS_DIR)) return { block: false };

  const staged = git("git diff --cached --name-only").split("\\n").filter(Boolean);
  if (!staged.length) return { block: false };
  if (!staged.some((f) => !f.startsWith("docs/"))) return { block: false };

  const branch = git("git branch --show-current");
  if (!branch) return { block: false };

  let plan = null;
  const commonDir = git("git rev-parse --git-common-dir");
  if (commonDir) {
    try {
      const coordClaims = path.join(fs.realpathSync(commonDir), "soloship", "claims");
      if (fs.existsSync(coordClaims)) {
        for (const c of fs.readdirSync(coordClaims)) {
          if (!c.endsWith(".json")) continue;
          const full = path.join(coordClaims, c);
          let body = "";
          try {
            body = fs.readFileSync(full, "utf8");
          } catch {
            continue;
          }
          if (body.includes(\`"branch":"\${branch}"\`)) {
            const cand = path.join(PLANS_DIR, c.replace(/\\.json$/, ""));
            if (fs.existsSync(cand)) {
              plan = cand;
              break;
            }
          }
        }
      }
    } catch {
      // ignore
    }
  }
  if (!plan) {
    const slug = branch.replace(/^(feat|fix|chore|refactor)\\//, "");
    for (const f of fs.readdirSync(PLANS_DIR)) {
      if (f === "README.md" || !f.endsWith(".md")) continue;
      if (f.includes(slug)) {
        plan = path.join(PLANS_DIR, f);
        break;
      }
    }
  }
  if (!plan) return { block: false };

  const body = fs.readFileSync(plan, "utf8");
  const m = body.match(/^status:\\s*"?([^"\\n]*?)"?\\s*$/m);
  let status = (m ? m[1] : "").trim().toLowerCase();
  if (status === "not started" || status === "not-started") status = "planned";

  if (status === "planned") {
    const today = new Date().toISOString().slice(0, 10);
    return {
      block: true,
      message:
        \`BLOCKED by plan-truth-gate: you are committing CODE on branch "\${branch}", but its plan (\${plan}) still says "status: planned" — i.e. the plan claims this work has not started. That is exactly how plans come to lie about themselves: the work ships, the status never moves, and the next agent reads "not started" and builds it a second time.\\n\\n\` +
        \`FIX (5 seconds): set the plan frontmatter to\\n  status: in-progress\\n  claimed_by: <this session>\\n  branch: \${branch}\\n  updated: \${today}\\nthen re-run the commit. Flip it to "done" when the work merges.\\n\\n\` +
        \`Escape hatch (requires a real reason): mkdir -p .ai && echo "why a lying plan is correct here" > \${PLAN_STATUS_ACK}\`,
    };
  }

  return { block: false };
}

run(evaluate);
`;
}

function planNamespaceSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildPlanNamespaceGateScript (src/hooks.ts).
const fs = require("fs");
const { run } = require("./_shared.cjs");

const PLANS_DIR = ${JSON.stringify(PLANS_DIR)};
const PLAN_STATUS_ACK = ${JSON.stringify(PLAN_STATUS_ACK)};
const PLAN_STATUS_RE = new RegExp(${JSON.stringify(PLAN_STATUSES.join("|"))});
const DRAFTS_DIR = "docs/drafts";
const HANDOFFS_DIR = "docs/handoffs";
const REPORTS_DIR = "docs/reports";
const DECISIONS_DIR = "docs/architecture/decisions";

function evaluate(n) {
  if (fs.existsSync(PLAN_STATUS_ACK)) return { block: false };

  const fp = n.toolInput.filePath || "";
  if (!fp) return { block: false };

  if (!fp.includes(\`\${PLANS_DIR}/\`) || !fp.endsWith(".md")) return { block: false };
  if (fp.includes(\`\${PLANS_DIR}/archive/\`) || fp.endsWith("/README.md")) return { block: false };

  const statusFrontmatter = new RegExp(\`status:\\\\s*"?(\${PLAN_STATUS_RE.source})\`);
  const diskStatusFrontmatter = new RegExp(\`^status:\\\\s*"?(\${PLAN_STATUS_RE.source})\`, "m");

  const tiHasStatus = statusFrontmatter.test(n.toolInput.content || "");
  const diskHasStatus = fs.existsSync(fp) && diskStatusFrontmatter.test(fs.readFileSync(fp, "utf8"));

  if (diskHasStatus || tiHasStatus) return { block: false };

  const today = new Date().toISOString().slice(0, 10);
  return {
    block: true,
    message:
      \`BLOCKED by plan-namespace-gate: "\${fp}" has no plan status frontmatter, and \${PLANS_DIR}/ holds live plans ONLY.\\n\\n\` +
      \`If this IS a plan, give it frontmatter:\\n  ---\\n  status: planned          # or: \${PLAN_STATUS_RE.source}\\n  date: \${today}\\n  ---\\n\\n\` +
      \`If it is NOT a plan, it belongs somewhere else:\\n  draft / design note / grill / brainstorm  ->  \${DRAFTS_DIR}/     (deleted when promoted to a plan)\\n  session handoff                           ->  \${HANDOFFS_DIR}/   (deleted when consumed)\\n  point-in-time report or snapshot          ->  \${REPORTS_DIR}/    (historical, never actionable)\\n  decision log / ADR                        ->  \${DECISIONS_DIR}/\\n\\n\` +
      \`Why: agents read \${PLANS_DIR}/ to decide what work is outstanding. Anything in there without a status is invisible to the plan-truth gate and indistinguishable from a live plan.\\n\\n\` +
      \`Escape hatch (requires a real reason): mkdir -p .ai && echo "reason" > \${PLAN_STATUS_ACK}\`,
  };
}

run(evaluate);
`;
}

function planMergeSource(): string {
  return `"use strict";
// GENERATED by Soloship — do not hand-edit. Regenerated by
// \`npx soloship upgrade\`. Ported from buildPlanMergeGateScript (src/hooks.ts).
const fs = require("fs");
const { run } = require("./_shared.cjs");

const PLANS_DIR = ${JSON.stringify(PLANS_DIR)};
const PLAN_STATUS_ACK = ${JSON.stringify(PLAN_STATUS_ACK)};
const OPEN_STATUSES = new Set(${JSON.stringify(PLAN_STATUSES_OPEN)});

function evaluate(n) {
  const cmd = n.toolInput.command || "";
  if (!/git\\s+merge/.test(cmd)) return { block: false };
  if (fs.existsSync(PLAN_STATUS_ACK)) return { block: false };
  if (!fs.existsSync(PLANS_DIR)) return { block: false };

  const today = new Date().toISOString().slice(0, 10);

  for (const f of fs.readdirSync(PLANS_DIR)) {
    if (f === "README.md" || !f.endsWith(".md")) continue;
    const full = \`\${PLANS_DIR}/\${f}\`;
    let body;
    try {
      body = fs.readFileSync(full, "utf8");
    } catch {
      continue;
    }
    const m = body.match(/^status:\\s*"?([^"\\n]*?)"?\\s*$/m);
    let status = (m ? m[1] : "").trim().toLowerCase();
    if (status === "not started" || status === "not-started") status = "planned";
    if (status === "active") status = "in-progress";
    if (!OPEN_STATUSES.has(status)) continue;

    const bm = body.match(/^branch:\\s*"?(\\S+)"?\\s*$/m);
    const pbranch = bm ? bm[1] : "";
    if (!pbranch) continue;
    if (!cmd.includes(pbranch)) continue;

    return {
      block: true,
      message:
        \`BLOCKED by plan-merge-gate: you are merging branch "\${pbranch}", but its plan (\${full}) still says "status: \${status}". After this merge the work is live — and if the status never moves, the plan will claim forever that this work was never finished. That is the exact defect this gate exists to prevent.\\n\\n\` +
        \`FIX: set the plan frontmatter to\\n  status: done\\n  progress: "<total>/<total>"\\n  updated: \${today}\\nremove the claimed_by line, then re-run the merge.\\n\\n\` +
        \`If the work is genuinely NOT complete and you are merging partial work on purpose, set an honest status instead (blocked / superseded) and say so in the plan.\\n\\n\` +
        \`Escape hatch (requires a real reason): mkdir -p .ai && echo "reason" > \${PLAN_STATUS_ACK}\`,
    };
  }

  return { block: false };
}

run(evaluate);
`;
}

const GATE_SOURCE: Record<GateName, () => string> = {
  "command-safety": commandSafetySource,
  "billing-confirmation": billingConfirmationSource,
  recurrence: recurrenceSource,
  "deploy-freshness": deployFreshnessSource,
  "deploy-discipline": deployDisciplineSource,
  "plan-truth": planTruthSource,
  "plan-merge": planMergeSource,
  "plan-namespace": planNamespaceSource,
};

function isGitIgnored(root: string, relativePath: string): boolean {
  try {
    // git check-ignore -q: exit 0 = ignored (no output needed, hence -q).
    execFileSync("git", ["check-ignore", "-q", relativePath], { cwd: root, stdio: "ignore" });
    return true;
  } catch (e) {
    // Exit 1 = not ignored (the expected, common case). Anything else (no
    // git, not a repo yet) means we can't ask — assume not ignored rather
    // than block installation outside a git repo.
    return false;
  }
}

// Writes _shared.cjs + every gate file into <root>/scripts/soloship-hooks/.
// Idempotent and host-agnostic: called once by whichever installer(s) run
// (Claude, Cursor, Codex, Antigravity may all be installing in the same
// pass), safe to call more than once in one `init`/`upgrade` run.
export function writeCommittedGateFiles(root: string): string[] {
  const dir = join(root, GATE_BASE_DIR, GATE_DIRNAME);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const written: string[] = [];
  const writeGate = (filename: string, source: string) => {
    // Parse-check before writing — a generated gate with a syntax error fails
    // OPEN (Cursor spawns it directly and treats a crash as "allow"), so a
    // broken generator would silently protect nothing while doctor reports
    // it installed. Same discipline already applied to the Cursor scripts.
    new Script(source, { filename });
    const full = join(dir, filename);
    writeFileSync(full, source);
    // 0o755: Cursor spawns these directly via their shebang-less path entry
    // (Node is invoked explicitly by the other three hosts' adapters, but
    // Cursor's hooks.json takes a bare path) — executable bit is load-bearing
    // there and harmless everywhere else.
    chmodSync(full, 0o755);
    const relative = join(GATE_BASE_DIR, GATE_DIRNAME, filename);
    // Defends against the general failure class (SOME project-specific
    // gitignore rule this repo's own history already proved can exist) —
    // not just the specific `.soloship/` case that motivated the directory
    // move above. A gate that installs into a path git will never commit is
    // a gate that never reaches a clone; fail loudly instead of shipping a
    // phantom protection, same precedent as the Cursor installer's dead-path
    // throw.
    if (isGitIgnored(root, relative)) {
      throw new Error(
        `Soloship wrote a gate file to ${relative}, but this project's .gitignore excludes that path — it would install but never reach a clone or cloud agent. This is a Soloship bug (the gate directory should never collide with a project's ignore rules) or a project .gitignore that needs a carve-out. Either way, fix the ignore rule before re-running init/upgrade.`
      );
    }
    written.push(relative);
  };

  writeGate("_shared.cjs", sharedHelperSource());
  for (const name of GATE_NAMES) {
    writeGate(`${name}.cjs`, GATE_SOURCE[name]());
  }

  return written;
}

// Absolute path to a gate file — used ONLY for Claude Code's
// `.claude/settings.local.json`, which is gitignored by design (per-checkout,
// never shipped to a clone), so an absolute path baked at install time is
// safe there and matches every other generated Claude command in this
// codebase.
export function gatePath(root: string, name: GateName): string {
  return join(root, GATE_BASE_DIR, GATE_DIRNAME, `${name}.cjs`);
}

// Claude's invocation: absolute path (see gatePath). No per-host argv — the
// gate file detects its caller from the stdin payload shape (see
// sharedHelperSource's detectHost).
export function gateInvocation(root: string, name: GateName): string {
  return `bash -c 'node "${gatePath(root, name)}"'`;
}

// Portable invocation for every COMMITTED config (.codex/hooks.json,
// .agents/hooks.json, and any future host config that ships in the clone).
// An absolute path baked at install time is a path that is only valid on the
// machine that ran the installer — exactly wrong for a file meant to be
// cloned elsewhere. `git rev-parse --show-toplevel` re-resolves the project
// root from wherever the host actually runs its hook commands (documented
// cwd varies by host and by version); every gate already requires git for
// its own logic, so this adds no new dependency. Cursor's own installer
// already uses a plain root-relative path for the same committed-file reason
// (`.cursor/hooks/...`, not an absolute path) — this is the same idea, just
// defended against an unknown/subdirectory cwd rather than assuming root.
export function portableGateInvocation(name: GateName): string {
  return `bash -c 'node "$(git rev-parse --show-toplevel)/${GATE_BASE_DIR}/${GATE_DIRNAME}/${name}.cjs"'`;
}
