import { existsSync, readdirSync, readFileSync, rmdirSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import { CURSOR_DIR, CURSOR_RULES_DIRNAME } from "./hooks.js";
import { SAFETY_GATE_FILENAMES, getSafetyGateRules } from "./safety-gates.js";

// Phase 2 of docs/plans/2026-08-27-one-source-of-truth-across-agent-hosts.md:
// the seven always-on safety-gate rules no longer get written into any host
// rules directory — they live once, as AGENTS.md's `## Safety gates` section
// (src/safety-gates.ts, rendered by generateAgentsMd in templates.ts). What
// remains here is PRUNING: delete any copy a previous Soloship version left
// behind in .claude/rules/, .codex/rules/, .cursor/rules/, .agents/rules/.
// getWorkflowRules() (re-exported from safety-gates.ts) stays for doctor and
// tests during the transition; after Phase 5 this file exports only
// RETIRED_WORKFLOW_RULES + SAFETY_GATE_FILENAMES.
export { getSafetyGateRules as getWorkflowRules, SAFETY_GATE_FILENAMES };

export async function installClaudeRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return pruneOnly(join(root, ".claude", "rules"), ".md");
}

export async function installCodexRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return pruneOnly(join(root, ".codex", "rules"), ".md");
}

export async function installAntigravityRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return pruneOnly(join(root, ".agents", "rules"), ".md");
}

export async function installCursorRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return pruneOnly(join(root, CURSOR_DIR, CURSOR_RULES_DIRNAME), CURSOR_RULE_EXT, {
    alsoDeleteIfGenerated: true,
  });
}

export const installRules = installClaudeRules;

// Cursor reads project rules from `.cursor/rules/*.mdc` and SILENTLY IGNORES
// plain `.md` files in that directory — a rule copied across with the wrong
// extension looks installed and protects nothing. Verified against
// https://cursor.com/docs/context/rules (2026-08-18).
const CURSOR_RULE_EXT = ".mdc";

/**
 * Workflow rules Soloship used to install as always-on files and no longer
 * does. Init and upgrade delete these from every host rules directory so a
 * diet does not leave the old essays sitting next to the short replacements.
 *
 * Planning, component-reuse, parameterize-constants, solution-search, and
 * browser-tooling-priority live in skills / AGENTS.md / the plan template.
 * Delegation-discipline and verification-sufficiency remain skill references.
 */
export const RETIRED_WORKFLOW_RULES = [
  "solution-search.md",
  "plan-materialization.md",
  "plan-rationale.md",
  "plan-lifecycle.md",
  "plan-artifact-lifecycle.md",
  "plan-claim-verification.md",
  "parameterize-constants.md",
  "browser-tooling-priority.md",
  "qa-plan-in-plans.md",
  "component-reuse.md",
  "delegation-discipline.md",
  "verification-sufficiency.md",
] as const;

// Every filename Soloship has ever generated into a host rules directory —
// the full prune list.
const ALL_KNOWN_RULE_FILENAMES: readonly string[] = [
  ...RETIRED_WORKFLOW_RULES,
  ...SAFETY_GATE_FILENAMES,
];

// Old Cursor .mdc files (pre-this-change) carried this exact note in their
// body — a second, content-based signal on top of the filename list, for the
// one host whose generated files were ever marked at all (Claude/Codex/
// Antigravity's copies of these 7 carried no such marker). Catches a
// Soloship-generated file the user happened to rename before this prune ran.
const CURSOR_GENERATED_MARKER = "<!-- GENERATED by Soloship from the packaged workflow rules.";

function pruneKnownRules(
  rulesDir: string,
  ext: string,
  opts: { alsoDeleteIfGenerated?: boolean } = {}
): string[] {
  const results: string[] = [];
  if (!existsSync(rulesDir)) return results;

  const known = new Set(ALL_KNOWN_RULE_FILENAMES.map((f) => f.replace(/\.md$/, ext)));
  for (const filename of readdirSync(rulesDir)) {
    if (!filename.endsWith(ext)) continue;
    const isKnown = known.has(filename);
    const isMarkedGenerated =
      opts.alsoDeleteIfGenerated &&
      !isKnown &&
      readFileSafe(join(rulesDir, filename))?.includes(CURSOR_GENERATED_MARKER);
    if (!isKnown && !isMarkedGenerated) continue;
    unlinkSync(join(rulesDir, filename));
    results.push(
      `${filename} (removed — now lives in AGENTS.md's Safety gates section${isMarkedGenerated ? "; matched by GENERATED marker, not filename" : ""})`
    );
  }
  return results;
}

function readFileSafe(path: string): string | null {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}

/** Everything left in `rulesDir` after pruning — user-authored content
 * Soloship must never touch. Callers report this so the user can decide
 * whether to move it into AGENTS.md, where every host actually reads it. */
function listSurvivors(rulesDir: string, ext: string): string[] {
  if (!existsSync(rulesDir)) return [];
  return readdirSync(rulesDir).filter((f) => f.endsWith(ext));
}

async function pruneOnly(
  rulesDir: string,
  ext: string,
  opts: { alsoDeleteIfGenerated?: boolean } = {}
): Promise<string[]> {
  const results: string[] = [];
  if (!existsSync(rulesDir)) {
    // Nothing was ever installed here — leave the directory absent rather
    // than creating an empty one now that Soloship writes nothing into it.
    return results;
  }

  results.push(...pruneKnownRules(rulesDir, ext, opts));

  const survivors = listSurvivors(rulesDir, ext);
  if (survivors.length > 0) {
    results.push(
      `${survivors.length} user-authored rule(s) left untouched: ${survivors.join(", ")}`
    );
  } else if (results.length > 0) {
    // Everything Soloship generated is gone and nothing else was ever added.
    unlinkOrLeaveEmpty(rulesDir);
  }

  return results;
}

// Once pruning empties a directory Soloship no longer writes into, remove
// the empty directory rather than leaving a bare `.claude/rules/` behind —
// but only if it is genuinely empty (rmdir fails harmlessly otherwise).
function unlinkOrLeaveEmpty(rulesDir: string): void {
  try {
    if (readdirSync(rulesDir).length === 0) {
      rmdirSync(rulesDir);
    }
  } catch {
    // Not empty, or some other host-specific file lives there — leave it.
  }
}
