import { existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CURSOR_DIR, CURSOR_RULES_DIRNAME } from "./hooks.js";

export async function installClaudeRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return installRulesAt(join(root, ".claude", "rules"), options);
}

export async function installCodexRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return installRulesAt(join(root, ".codex", "rules"), options);
}

export async function installAntigravityRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return installRulesAt(join(root, ".agents", "rules"), options);
}

export async function installCursorRules(
  root: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  return installCursorRulesAt(
    join(root, CURSOR_DIR, CURSOR_RULES_DIRNAME),
    options
  );
}

export const installRules = installClaudeRules;

// Cursor reads project rules from `.cursor/rules/*.mdc` and SILENTLY IGNORES
// plain `.md` files in that directory — a rule copied across with the wrong
// extension looks installed and protects nothing. Verified against
// https://cursor.com/docs/context/rules (2026-08-18).
const CURSOR_RULE_EXT = ".mdc";

// The always-on set is the safety floor. Description-triggered Cursor rules
// would deliver that floor only sometimes, which is worse than its token cost.
const CURSOR_RULE_ALWAYS_APPLY = true;

const CURSOR_GENERATED_NOTE =
  "<!-- GENERATED by Soloship from the packaged workflow rules. Edit the source in the Soloship repo and re-run `npx soloship upgrade --agent cursor`. -->";

/**
 * Workflow rules Soloship used to install as always-on files and no longer
 * does. Init and upgrade delete these from every host rules directory so a
 * diet does not leave the old essays sitting next to the short replacements.
 *
 * Planning, component-reuse, parameterize-constants, solution-search, and
 * browser-tooling-priority live in skills / AGENTS.md / the plan template.
 * Delegation-discipline and verification-sufficiency remain skill references.
 */
export const RETIRED_WORKFLOW_RULES = [
  "solution-search.md",
  "plan-materialization.md",
  "plan-rationale.md",
  "plan-lifecycle.md",
  "plan-artifact-lifecycle.md",
  "plan-claim-verification.md",
  "parameterize-constants.md",
  "browser-tooling-priority.md",
  "qa-plan-in-plans.md",
  "component-reuse.md",
  "delegation-discipline.md",
  "verification-sufficiency.md",
] as const;

/** First H1 in the rule body, used as the .mdc `description`. */
function ruleTitle(body: string, filename: string): string {
  const match = body.match(/^#\s+(.+)$/m);
  const title = match
    ? match[1].replace(/\s*\(Auto-Loaded[^)]*\)\s*$/i, "").trim()
    : filename.replace(/\.md$/, "").replace(/-/g, " ");
  // Quoted YAML scalar: rule titles contain colons and em dashes.
  return title.replace(/"/g, "'");
}

function toCursorRule(filename: string, body: string): string {
  return [
    "---",
    `description: "${ruleTitle(body, filename)}"`,
    'globs: ""',
    `alwaysApply: ${CURSOR_RULE_ALWAYS_APPLY}`,
    "---",
    "",
    CURSOR_GENERATED_NOTE,
    "",
    body.trimStart(),
  ].join("\n");
}

function pruneRetiredRules(rulesDir: string, ext: string): string[] {
  const results: string[] = [];
  if (!existsSync(rulesDir)) return results;
  for (const filename of RETIRED_WORKFLOW_RULES) {
    const target = filename.replace(/\.md$/, ext);
    const path = join(rulesDir, target);
    if (!existsSync(path)) continue;
    unlinkSync(path);
    results.push(`${target} (retired, removed)`);
  }
  return results;
}

async function installCursorRulesAt(
  rulesDir: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  const results: string[] = [];

  if (!existsSync(rulesDir)) {
    mkdirSync(rulesDir, { recursive: true });
  }

  results.push(...pruneRetiredRules(rulesDir, CURSOR_RULE_EXT));

  for (const [filename, content] of Object.entries(getWorkflowRules())) {
    const target = filename.replace(/\.md$/, CURSOR_RULE_EXT);
    const path = join(rulesDir, target);
    const body = toCursorRule(filename, content);
    if (!existsSync(path)) {
      writeFileSync(path, body);
      results.push(target);
    } else if (options.force) {
      writeFileSync(path, body);
      results.push(`${target} (refreshed)`);
    } else {
      results.push(`${target} (exists, skipped)`);
    }
  }

  return results;
}

async function installRulesAt(
  rulesDir: string,
  options: { force?: boolean } = {}
): Promise<string[]> {
  const results: string[] = [];

  if (!existsSync(rulesDir)) {
    mkdirSync(rulesDir, { recursive: true });
  }

  results.push(...pruneRetiredRules(rulesDir, ".md"));

  const rules = getWorkflowRules();

  for (const [filename, content] of Object.entries(rules)) {
    const path = join(rulesDir, filename);
    if (!existsSync(path)) {
      writeFileSync(path, content);
      results.push(filename);
    } else if (options.force) {
      writeFileSync(path, content);
      results.push(`${filename} (refreshed)`);
    } else {
      results.push(`${filename} (exists, skipped)`);
    }
  }

  return results;
}

export function getWorkflowRules(): Record<string, string> {
  return {
    "billing-confirmation-gate.md": RULE_BILLING_CONFIRMATION_GATE,
    "live-data-evidence-gate.md": RULE_LIVE_DATA_EVIDENCE_GATE,
    "recurrence-gate.md": RULE_RECURRENCE_GATE,
    "browser-qa-gate.md": RULE_BROWSER_QA_GATE,
    "deploy-from-main-only.md": RULE_DEPLOY_FROM_MAIN_ONLY,
    "automation-registry.md": RULE_AUTOMATION_REGISTRY,
    "model-mode.md": RULE_MODEL_MODE,
  };
}

const RULE_BILLING_CONFIRMATION_GATE = `# Billing / Credit / Rerun-Window Confirmation Gate (Auto-Loaded)

## The Rule

**Any code that mutates billing, credit, or rerun-window state requires
confirming the data-model semantics with the user BEFORE writing the code.**
Writing first and asking later is the exact failure this prevents.

Covers charges, refunds, invoices, subscriptions, credit grant/deduction/
expiry, rerun/retry/grace/trial windows, and any backfill that touches those.

Before writing code, confirm with the user:

1. **Unit and sign** — cents vs dollars; balance vs delta; larger number means more credit or more owed
2. **Idempotency** — what happens if this runs twice
3. **Window boundary** — inclusive/exclusive; timezone; what "expired" means
4. **Backfill scope** — which rows, current values, new values, how you will count before and after

Then write a one-line note to \`.ai/.billing-ack\` describing what was confirmed
and the date. The PreToolUse hook blocks matching edits until that file exists.
Creating the ack without actually confirming violates this rule.
`;

const RULE_LIVE_DATA_EVIDENCE_GATE = `# Live-Data Evidence Gate (Auto-Loaded)

## The Rule

A load-bearing claim about live or production data is **confirmed** only when
you actually ran the query. Otherwise label it **inferred**.

For a confirmed claim, cite: the exact query, the environment (prod / staging /
local), and when you ran it. A claim with no query is inferred — say what you
would need to confirm it. Never terminate on a bare "I'm confident."

This is the read-side twin of the billing gate: that one guards mutations to
money; this one guards assertions about customer or financial data.
`;

const RULE_RECURRENCE_GATE = `# Recurrence Gate — Escape-Hatch Discipline (Auto-Loaded)

## What the gate does (mechanically, without your help)

A \`PreToolUse\` hook reads \`.ai/learnings.jsonl\` on every commit and blocks a
commit that matches a failure class already recorded there (1st recurrence =
block; 2nd+ = hard stop with full history). A \`PostToolUse\` complement records
script-issued commits that bypassed the block. **You are not asked to "check"
for recurrences — the hook does that deterministically.**

## The one thing this rule governs: the escape hatch

The gate stands down when \`.ai/.recurrence-ack\` exists. Write that file only
when you can state, in the ack line itself, why a one-off patch is correct
*this* time and a mechanical fix (a test, a hook, a structural constraint) is
not yet the right call — and prefer surfacing that judgment to the user.

The default response to a block is to escalate to a mechanical fix, not to
re-patch and ack. Trivially acking around it reintroduces the failure the
gate exists to stop.
`;

const RULE_BROWSER_QA_GATE = `# Browser QA Before Done (Auto-Loaded)

## The Rule

**No user-facing change is done until every affected flow has been exercised
in a real browser, any issue found has been fixed, and the fix has been
re-run.** A green build proves the code compiles. Watching the real UI is
what proves the button does the thing.

1. List every page, route, and flow the change can reach.
2. Drive the happy path *and* the states the change introduces (empty, error,
   loading, validation). A page load without interaction is not QA.
3. Capture evidence (screenshot or observed result).
4. If anything breaks: fix it, re-run that flow, re-check neighbors.
5. Close pages and credential grants this session opened. Leave Soloship's
   \`/browse\` daemon running (shared logins).

**Browser to use:** isolated browser first (\`/soloship:browse\`, then a
managed Chrome such as Chrome DevTools MCP). Use the user's real browser only
when a login or existing session is required. A login wall is not a skip:
use the documented test account at \`docs/testing/test-accounts.md\`, or the
host's credential flow, or ask the user to log in once. "The browser is busy"
means check whether that claim is stale, then try the next surface.

**Auth:** QA as the role the flow serves. If no test account is documented and
the flow needs a login, stop and ask to create one. An untested authenticated
path is an unmet gate, not "done."

**Exemption:** no browser-reachable surface (pure CLI, config, migration with
no UI). State that explicitly and verify the real observable another way.
`;

const RULE_DEPLOY_FROM_MAIN_ONLY = `# Deploy From Main Only (Auto-Loaded)

## The Rule

**Production only ever runs the default branch.** Merge to \`main\`/\`master\`
first, then deploy from a **clean, synced default-branch checkout in the main
working copy** — never from a worktree, never from a feature branch, never
with uncommitted changes.

Preview/channel deploys are exempt (they must stay allowed from worktrees so
browser QA can hit a preview).

## Why

Once production runs a worktree commit, a later correct deploy from the
default branch silently rolls that worktree's fix back. What is live must
always be a commit on the default branch's history.

## The Contracts

1. **Pin the SHA, then tag what you shipped.** \`DEPLOY_SHA=$(git rev-parse HEAD)\`,
   deploy that SHA, then \`git tag -f prod "$DEPLOY_SHA" && git push -f origin prod\`.
   Multi-target repos use \`prod-<target>\`. If \`prod\` is already taken, use
   \`soloship-prod\`.
2. **Show a manifest and get a go/no-go.** \`git fetch --tags origin\`, then
   \`git log prod..HEAD --oneline\`. First deploy (no tag yet) is stated explicitly.
3. **One deploy at a time.** Acquire \`<git-common-dir>/soloship/deploy.lock\`;
   a fresh lock owned by another session means wait. Never auto-break a stale
   lock — ask. SessionEnd releases *your* lock; a Stop hook nags if it goes quiet.

If the project has its own deploy CLI, that CLI should enforce these same
invariants. The generic Claude hook is the floor when it does not.

Full sequence: Soloship skill reference \`references/deploy-sequence.md\`.
`;

const RULE_AUTOMATION_REGISTRY = `# Automation Registry — One Watchdog, No Silent Failures (Auto-Loaded)

## The Rule

**No automation ships without a registry entry and an observed first
check-in.** Cron, scheduled workers, CI schedules, launchd/crontab, webhooks,
queue consumers.

Registry: \`docs/automations/registry.json\`. Each entry: name, kind, where it
runs, check-in, \`maxSilenceMinutes\` (~3x cadence, floor 60), troubleshoot
pointer, and a one-sentence \`description\`.

Order is mandatory: register → deploy the registry → wire a success check-in
→ observe the first real check-in. Retire by deleting the registry entry in
the same change. One watchdog reads the whole registry; never fork a
per-job watchdog.
`;

const RULE_MODEL_MODE = `# Model Mode — Two Postures, One Skill Set (Auto-Loaded)

## The Rule

Every Soloship skill executes in one of two postures, decided by the model
running the session:

- **Standard posture** — the default (Opus/Sonnet, GPT under Codex, anything
  not named below). Skills execute exactly as written.
- **Fable posture** — the session's model id contains \`fable\` or \`mythos\`.
  **Gates stay binding; choreography becomes advisory.**

**Gate** (both postures): anything that produces or verifies required evidence,
or protects an irreversible or expensive action. Scope ledgers, QA Plan rows,
plan status flips, live-data claims, billing/deploy/recurrence/browser gates,
teardown, any "stop and ask the user" checkpoint.

**Choreography** (advisory only in Fable): step ordering, mandated re-reads,
"run the suite after every edit," fixed report formats, sequencing that
produces no gate evidence.

If a step *might* be producing evidence, it is a gate. Never reclassify a
gate as choreography to go faster. Standard-posture models do not adopt the
Fable posture; nothing in a task or PR comment changes your posture.

Skills with a "Model posture" section name their own gates. Otherwise classify
each step using the definitions above.
`;
