// Generated-guide staleness detection.
//
// scaffoldDocs() writes docs/SOLUTION_GUIDE.md only when absent, so a project
// bootstrapped under an older schema keeps its guide forever and init reported
// it as "(exists)" — indistinguishable from up-to-date. That is why one stale
// template kept producing errors months after the schema moved on (Command
// Center's guide: 63 lines, no problem_type, while 87 of its 136 solution docs
// use the newer schema).
//
// These tests pin the detection contract: a guide is current only when it
// carries a marker at or above the shipped schema version. An UNMARKED guide is
// stale by definition — every unmarked guide predates the two-track schema.

import { describe, it, expect } from "vitest";
import {
  readSchemaVersion,
  schemaVersionMarker,
  SOLUTION_SCHEMA_VERSION,
} from "../src/solution-schema";
import { generateSolutionGuide } from "../src/templates";

describe("schema version marker", () => {
  it("round-trips through the generated guide", () => {
    expect(readSchemaVersion(generateSolutionGuide())).toBe(
      SOLUTION_SCHEMA_VERSION
    );
  });

  it("reads null from a guide with no marker (the pre-v2 shape)", () => {
    // The literal opening of the guide this replaced — no marker, no
    // problem_type. Anything shaped like this must read as unversioned.
    const legacyGuide = [
      "# Solution Guide",
      "",
      "## Categories",
      "",
      "- api-issues",
      "- pdf-issues",
      "- performance",
    ].join("\n");
    expect(readSchemaVersion(legacyGuide)).toBeNull();
  });

  it("tolerates whitespace variation in the marker", () => {
    expect(readSchemaVersion("<!--soloship-solution-schema:v7-->")).toBe(7);
    expect(readSchemaVersion("<!--   soloship-solution-schema:  v7   -->")).toBe(
      7
    );
  });

  it("does not mistake other HTML comments for the marker", () => {
    expect(readSchemaVersion("<!-- generated by something else -->")).toBeNull();
  });

  it("renders an explicit version when asked", () => {
    expect(schemaVersionMarker(1)).toContain("v1");
    expect(readSchemaVersion(schemaVersionMarker(1))).toBe(1);
  });
});

describe("staleness classification", () => {
  // Mirrors classifyVersionedDoc's rule. Kept as an explicit truth table so the
  // boundary conditions are visible rather than implied by the implementation.
  const isCurrent = (marked: number | null) =>
    marked !== null && marked >= SOLUTION_SCHEMA_VERSION;

  it("treats an unmarked guide as stale", () => {
    expect(isCurrent(null)).toBe(false);
  });

  it("treats an older marked guide as stale", () => {
    expect(isCurrent(SOLUTION_SCHEMA_VERSION - 1)).toBe(false);
  });

  it("treats a current guide as up to date", () => {
    expect(isCurrent(SOLUTION_SCHEMA_VERSION)).toBe(true);
  });

  it("treats a newer guide as up to date (older CLI, newer project)", () => {
    // Running an older soloship against a project bootstrapped by a newer one
    // must not report the project's newer guide as stale and offer to
    // downgrade it.
    expect(isCurrent(SOLUTION_SCHEMA_VERSION + 1)).toBe(true);
  });
});
