// Rule migration into AGENTS.md — behavioral regression tests.
//
// Phase 2 of docs/plans/2026-08-27-one-source-of-truth-across-agent-hosts.md:
// installClaudeRules/installCodexRules/installAntigravityRules/
// installCursorRules stop WRITING the 7 safety-gate rule files (they moved to
// AGENTS.md's Safety gates section) and become pure pruners — delete
// Soloship's own prior copies, never touch user-authored files, never
// recreate a directory that was never there.

import { describe, it, expect } from "vitest";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  installClaudeRules,
  installCodexRules,
  installAntigravityRules,
  installCursorRules,
} from "../src/rules";
import { SAFETY_GATE_FILENAMES } from "../src/safety-gates";

function tmpRoot(): string {
  return mkdtempSync(join(tmpdir(), "soloship-rules-migration-"));
}

describe("installClaudeRules / installCodexRules / installAntigravityRules — prune only, never write", () => {
  const cases: [string, (root: string) => Promise<string[]>, string][] = [
    ["Claude", installClaudeRules, ".claude/rules"],
    ["Codex", installCodexRules, ".codex/rules"],
    ["Antigravity", installAntigravityRules, ".agents/rules"],
  ];

  for (const [label, installer, relDir] of cases) {
    it(`${label}: never creates a rules directory that didn't already exist`, async () => {
      const root = tmpRoot();
      try {
        await installer(root);
        expect(existsSync(join(root, relDir))).toBe(false);
      } finally {
        rmSync(root, { recursive: true, force: true });
      }
    });

    it(`${label}: deletes a pre-existing generated safety-gate file, never rewrites it`, async () => {
      const root = tmpRoot();
      try {
        const dir = join(root, relDir);
        mkdirSync(dir, { recursive: true });
        const name = SAFETY_GATE_FILENAMES[0];
        writeFileSync(join(dir, name), "# stale generated copy\n");

        const results = await installer(root);

        expect(existsSync(join(dir, name))).toBe(false);
        expect(results.join("\n")).toContain("Safety gates section");
      } finally {
        rmSync(root, { recursive: true, force: true });
      }
    });

    it(`${label}: leaves a user-authored rule with an unrelated name untouched and reports it`, async () => {
      const root = tmpRoot();
      try {
        const dir = join(root, relDir);
        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, "my-custom-rule.md"), "# Mine, not Soloship's\n");

        const results = await installer(root);

        expect(existsSync(join(dir, "my-custom-rule.md"))).toBe(true);
        expect(results.join("\n")).toContain("my-custom-rule.md");
        expect(results.join("\n")).toContain("user-authored");
      } finally {
        rmSync(root, { recursive: true, force: true });
      }
    });

    it(`${label}: removes the directory once pruning empties it`, async () => {
      const root = tmpRoot();
      try {
        const dir = join(root, relDir);
        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, SAFETY_GATE_FILENAMES[0]), "# stale\n");

        await installer(root);

        expect(existsSync(dir)).toBe(false);
      } finally {
        rmSync(root, { recursive: true, force: true });
      }
    });
  }
});

describe("installCursorRules — .mdc, plus GENERATED-marker fallback", () => {
  it("deletes a pre-existing generated safety-gate .mdc, never rewrites it", async () => {
    const root = tmpRoot();
    try {
      const dir = join(root, ".cursor", "rules");
      mkdirSync(dir, { recursive: true });
      const stem = SAFETY_GATE_FILENAMES[0].replace(/\.md$/, "");
      writeFileSync(join(dir, `${stem}.mdc`), "---\ndescription: x\n---\nstale\n");

      await installCursorRules(root);

      expect(existsSync(join(dir, `${stem}.mdc`))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("deletes a RENAMED generated file caught only by its GENERATED marker", async () => {
    const root = tmpRoot();
    try {
      const dir = join(root, ".cursor", "rules");
      mkdirSync(dir, { recursive: true });
      writeFileSync(
        join(dir, "renamed-by-user.mdc"),
        [
          "---",
          'description: "x"',
          "---",
          "",
          "<!-- GENERATED by Soloship from the packaged workflow rules. Edit the source in the Soloship repo and re-run `npx soloship upgrade --agent cursor`. -->",
          "",
          "stale content",
        ].join("\n")
      );

      const results = await installCursorRules(root);

      expect(existsSync(join(dir, "renamed-by-user.mdc"))).toBe(false);
      expect(results.join("\n")).toContain("GENERATED marker");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("leaves a genuinely user-authored .mdc (no marker) untouched", async () => {
    const root = tmpRoot();
    try {
      const dir = join(root, ".cursor", "rules");
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, "my-own.mdc"), "---\ndescription: mine\n---\nnot Soloship's\n");

      await installCursorRules(root);

      expect(existsSync(join(dir, "my-own.mdc"))).toBe(true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
